// Generated by hand to stay in lockstep with `scripts/spum-import.ts`. When
// adding parts or clips, update both lists together — the importer reads the
// PNG/atlas/anim files, this file types them for the runtime + admin UI.
//
// Part keys are flat per slot regardless of which pack imported them. The
// Modern* prefix vs Legacy* numeric naming is preserved from SPUM's source
// folders so re-imports stay 1:1 with `temp/SPUM/`.

const HAIR_PARTS = [
  // ModernPackVer1. m11/m12/m13 imported for E10 preset coverage.
  "Hair_m01", "Hair_m02", "Hair_m03", "Hair_m04", "Hair_m05",
  "Hair_m06", "Hair_m07", "Hair_m08", "Hair_m09", "Hair_m10",
  "Hair_m11", "Hair_m12", "Hair_m13",
  // Legacy
  "Hair_1", "Hair_2", "Hair_3", "Hair_4", "Hair_5",
  "Hair_6", "Hair_7", "Hair_8", "Hair_9",
  // Ver300
  "New_Hair_01", "New_Hair_02", "New_Hair_03", "New_Hair_04", "New_Hair_05",
  "New_Hair_06", "New_Hair_07", "New_Hair_08", "New_Hair_09", "New_Hair_10",
  "New_Hair_11", "New_Hair_12", "New_Hair_13", "New_Hair_14", "New_Hair_15",
  "New_Hair_16", "New_Hair_17", "New_Hair_18", "New_Hair_19", "New_Hair_20",
  // RetroHeroes — class-themed. Source typo `Hair_Arhcer_2.png` is cleaned
  // to `Hair_Archer_2` at the part-key level; importer keeps the literal
  // misspelling on the source path.
  "Hair_Archer_1", "Hair_Archer_2",
  "Hair_Healer_1", "Hair_Healer_2",
  "Hair_Knight_1", "Hair_Knight_2",
  "Hair_Rogue_1", "Hair_Rogue_2",
  "Hair_Sorcerer", "Hair_Sorceress",
  // Ver121 — the original SPUM 1.2 "Knight pack" addon. 13 hairs in a
  // visually-distinct older style; preserves SPUM's `Normal_*` source-name
  // prefix verbatim so the part keys stay prefix-distinguishable from every
  // other pack.
  "Normal_Hair1", "Normal_Hair2", "Normal_Hair3", "Normal_Hair4",
  "Normal_Hair5", "Normal_Hair6", "Normal_Hair7", "Normal_Hair8",
  "Normal_Hair9", "Normal_Hair10", "Normal_Hair11", "Normal_Hair12",
  "Normal_Hair13",
  // Custom one-off imports — managed by scripts/custom-part-import.ts.
  // custom-parts:BEGIN hair
  // custom-parts:END hair
] as const;

const CLOTH_PARTS = [
  // ModernPackVer1. E10 expanded the imported variants from 20 → 63 (every
  // cloth PNG SPUM ships in this pack) so the 200 Modern character-preset
  // prefabs can resolve cleanly against the catalog. Each entry is a `_c1`/
  // `_c2`/`_g` recolour of the base outfit (girl variant / colour swatches).
  "dress_1", "dress_1_c1", "dress_1_c2", "dress_1_g",
  "dress_2", "dress_2_c1", "dress_2_c2", "dress_2_g",
  "dress_3", "dress_3_c1", "dress_3_c2", "dress_3_g",
  "dress_4", "dress_4_c1", "dress_4_c2", "dress_4_g",
  "dress_5", "dress_5_c1", "dress_5_c2", "dress_5_g",
  "farmer", "farmer_c1", "farmer_c2", "farmer_g",
  "hoodie", "hoodie_c1", "hoodie_c2",
  "suit_1", "suit_1_c1", "suit_1_c2", "suit_1_g",
  "suit_2", "suit_2_c1", "suit_2_c2", "suit_2_g",
  "suit_3", "suit_3_c1", "suit_3_c2", "suit_3_g",
  "tee_1", "tee_1_c1", "tee_1_g1", "tee_1_g2",
  "tee_2", "tee_2_c1", "tee_2_c2", "tee_2_g",
  "tee_3", "tee_3_c1", "tee_3_c2", "tee_3_g",
  "winter1", "winter1_c1", "winter1_c2", "winter1_g",
  "winter2", "winter2_c1", "winter2_c2", "winter2_g",
  "winter3", "winter3_c1", "winter3_c2", "winter3_g",
  // Legacy. 3-region atlases (Right/Body/Left); no `Body_b` back-of-body
  // slice — the renderer's missing-region skip handles it, same pattern as
  // ModernPackVer1's sleeveless `tee_2`.
  "Cloth_1", "Cloth_2", "Cloth_3", "Cloth_4", "Cloth_5",
  "Cloth_6", "Cloth_7", "Cloth_8", "Cloth_9", "Cloth_10",
  "Cloth_11", "Cloth_12", "F_SR_Cloth",
  // Ver300. 3-region atlases (Body/Left/Right).
  "New_Cloth_01", "New_Cloth_02", "New_Cloth_03", "New_Cloth_04",
  "New_Cloth_05", "New_Cloth_06", "New_Cloth_07", "New_Cloth_08",
  "New_Cloth_09", "New_Cloth_10", "New_Cloth_11", "New_Cloth_12",
  // RetroHeroes — class-themed; 3-region atlases.
  "Cloth_Archer_1", "Cloth_Archer_2",
  "Cloth_Healer_1", "Cloth_Healer_2",
  "Cloth_Knight_1", "Cloth_Knight_2",
  "Cloth_Rogue_1", "Cloth_Rogue_2",
  "Cloth_Sorcerer", "Cloth_Sorceress",
  // Undead. 3-region atlases (Body/Left/Right).
  "Undead_Cloth_01", "Undead_Cloth_02", "Undead_Cloth_03", "Undead_Cloth_04",
  "Undead_Cloth_05", "Undead_Cloth_06", "Undead_Cloth_07",
  // Ver121 — single cloth atlas (3-region Body/Right/Left like the other
  // multi-region cloth packs).
  "Normal_Cloth1",
  // Custom parts — managed by the Part Studio (/admin/spum?tab=parts).
  // custom-parts:BEGIN cloth
  // custom-parts:END cloth
] as const;

const PANT_PARTS = [
  // ModernPackVer1 (slot is footwear; Legacy ships none)
  "Foot_m01", "Foot_m02", "Foot_m03", "Foot_m04", "Foot_m05",
  // Ver300. 2-region atlas (Left/Right), same shape as Modern footwear.
  "New_Pant_01", "New_Pant_02", "New_Pant_03", "New_Pant_04",
  "New_Pant_05", "New_Pant_06", "New_Pant_07", "New_Pant_08",
  "New_Pant_09", "New_Pant_10", "New_Pant_11", "New_Pant_12",
  // RetroHeroes — class-themed. SPUM ships no `Pant_Archer_1` (Archer only
  // has the `_2` variant); Sorcerer/Sorceress each get a single un-numbered
  // entry.
  "Pant_Archer_2",
  "Pant_Healer_1", "Pant_Healer_2",
  "Pant_Knight_1", "Pant_Knight_2",
  "Pant_Rogue_1", "Pant_Rogue_2",
  "Pant_Sorcerer", "Pant_Sorceress",
  // Undead. 2-region atlas (Left/Right) — same shape as Modern footwear.
  "Undead_Pant_01", "Undead_Pant_02", "Undead_Pant_03",
  "Undead_Pant_04", "Undead_Pant_05",
  // Custom parts — managed by the Part Studio (/admin/spum?tab=parts).
  // custom-parts:BEGIN pant
  // custom-parts:END pant
] as const;

// 11 base helmets × 5 colour variants (base, _black, _blonde, _brown, _color).
// Single-region single-sprite atlases; one render at `12_Helmet2` (sortingOrder
// 12) drops them above hair (6) and the head (5), but below the eyes — those
// ride a constant lift to 14/15 (see EYE_Z_LIFT). See SLOT_REGION_TO_BONE for
// the wiring and `MODERN_HELMET_PARTS` in `scripts/spum-import.ts` for the
// flattened source-name → part-key mapping.
const HELMET_PARTS = [
  // ModernPackVer1
  "Helmet_m01", "Helmet_m01_black", "Helmet_m01_blonde", "Helmet_m01_brown", "Helmet_m01_color",
  "Helmet_m02", "Helmet_m02_black", "Helmet_m02_blonde", "Helmet_m02_brown", "Helmet_m02_color",
  "Helmet_m03", "Helmet_m03_black", "Helmet_m03_blonde", "Helmet_m03_brown", "Helmet_m03_color",
  "Helmet_m04", "Helmet_m04_black", "Helmet_m04_blonde", "Helmet_m04_brown", "Helmet_m04_color",
  "Helmet_m05", "Helmet_m05_black", "Helmet_m05_blonde", "Helmet_m05_brown", "Helmet_m05_color",
  "Helmet_m06", "Helmet_m06_black", "Helmet_m06_blonde", "Helmet_m06_brown", "Helmet_m06_color",
  "Helmet_m07", "Helmet_m07_black", "Helmet_m07_blonde", "Helmet_m07_brown", "Helmet_m07_color",
  "Helmet_m08", "Helmet_m08_black", "Helmet_m08_blonde", "Helmet_m08_brown", "Helmet_m08_color",
  "Helmet_m09", "Helmet_m09_black", "Helmet_m09_blonde", "Helmet_m09_brown", "Helmet_m09_color",
  "Helmet_m10", "Helmet_m10_black", "Helmet_m10_blonde", "Helmet_m10_brown", "Helmet_m10_color",
  "Helmet_m11", "Helmet_m11_black", "Helmet_m11_blonde", "Helmet_m11_brown", "Helmet_m11_color",
  // Ver300. Single-region (no colour variants in this pack).
  "New_Helmet_01", "New_Helmet_02", "New_Helmet_03", "New_Helmet_04",
  "New_Helmet_05", "New_Helmet_06", "New_Helmet_07", "New_Helmet_08",
  "New_Helmet_09", "New_Helmet_10",
  // RetroHeroes — class-themed; single-region.
  "Helmet_Archer_1", "Helmet_Archer_2",
  "Helmet_Healer_1", "Helmet_Healer_2",
  "Helmet_Knight_1", "Helmet_Knight_2",
  "Helmet_Rogue_1", "Helmet_Rogue_2",
  "Helmet_Sorcerer", "Helmet_Sorceress",
  // Undead. Single-region (skull caps, hoods, bone crowns).
  "Undead_Helmet_01", "Undead_Helmet_02", "Undead_Helmet_03", "Undead_Helmet_04",
  "Undead_Helmet_05", "Undead_Helmet_06", "Undead_Helmet_07",
  // Ver121 — 3 single-sprite helmets (knight pack era).
  "Normal_Helmet1", "Normal_Helmet2", "Normal_Helmet3",
  // Custom one-off imports — managed by scripts/custom-part-import.ts.
  // custom-parts:BEGIN helmet
  "Custom_ChefHat",
  "Custom_bowlerhat",
  "Custom_teahat",
  // custom-parts:END helmet
] as const;

const BODY_PARTS = [
  // ModernPackVer1 references Legacy's Human_1.png, so it lands in `body`
  // regardless of which pack you import.
  "Human_1",
  // Legacy
  "Devil_1", "Elf_1", "Elf_2",
  "Human_2", "Human_3", "Human_4", "Human_5",
  "Orc_1", "Orc_2", "Orc_3", "Orc_4",
  "Skelton_1",
  // Undead. Multi-region atlases (Head/Body/Arm_L/Arm_R/Foot_L/Foot_R) —
  // same shape as Legacy's `Human_*`. Mix of zombie + skeleton bodies; the
  // 4 Undead prefab variants (NormalZombie/EliteZomibes/SpecailZombies/
  // TeamSkeleton) compose different picks from this catalogue.
  "Zombie_1", "Zombie_2", "Zombie_3",
  "Zombie_4", "Zombie_5", "Zombie_6",
  // Custom parts — managed by the Part Studio (/admin/spum?tab=parts).
  // custom-parts:BEGIN body
  "Custom_body1",
  "Custom_saveagain",
  "Custom_saveagain2",
  "Custom_saveagain3",
  "Custom_test1",
  // custom-parts:END body
] as const;

// Eye sprites live only in Legacy's `0_Eye/` folder; Modern's prefab references
// them via `Addons/Legacy/0_Unit/0_Sprite/0_Eye/Eye2`. Each PNG is a two-region
// atlas (`Back` = sclera, `Front` = iris) used by the renderer to compose one
// eye-pair onto the head. `Eye_Close` is the eyelash sprite that always loads
// alongside the user's pick — it renders on the P_LClose/P_RClose bones and
// becomes visible during clips that drive eye-close via m_IsActive curves.
const EYE_PARTS = [
  "Eye", "Eye0", "Eye1", "Eye2", "Eye3", "Eye4", "Eye5",
  "Eye6", "Eye7", "Eye8", "Eye9", "Eye10", "Eye11", "Eye16",
  "Eye_Close",
  // Custom — Cyclops-style yellow oval outline + red iris bar. Renders at
  // both eye bones (no per-bone customisation), so the character gets two
  // mini-visor eyes side by side rather than one continuous visor.
  "Eye_Cyclops",
  // Custom parts — managed by the Part Studio (/admin/spum?tab=parts).
  // custom-parts:BEGIN eye
  "Custom_bigeye",
  // custom-parts:END eye
] as const;

// FaceHair is misleadingly named: in Modern it's "face accessories" (face_lip
// = mouth, face_cheek = blush, face_eyelash, face_acc_m01..06 = glasses);
// Legacy/Ver121 use it for the more traditional mustaches/beards. This is the
// only path to characters having a visible mouth — the body Head slice ships
// blank. Single-region single-sprite atlases. One slot per character (the
// prefab's two FaceHair entries are two character variants, not stacking).
const FACEHAIR_PARTS = [
  // ModernPackVer1
  "face_acc_m01", "face_acc_m02", "face_acc_m03",
  "face_acc_m04", "face_acc_m05", "face_acc_m06",
  "face_cheek", "face_eyelash", "face_lip",
  // Legacy
  "FaceHair_1", "FaceHair_2", "FaceHair_3", "FaceHair_4", "FaceHair_5",
  // Ver121 — 2 mustache entries from the original Knight pack.
  "Normal_Mustache1", "Normal_Mustache2",
  // Custom one-off imports — managed by scripts/custom-part-import.ts.
  // custom-parts:BEGIN faceHair
  // custom-parts:END faceHair
] as const;

// Armor slot — chest/shoulder overlay. spriteMode:2 atlases with three named
// regions (Right/Body/Left) mirroring Cloth's shape. Renders across three
// bones: BodyArmor (sortingOrder 2 — paints on top of body z=4? actually
// below; but renderer ordering with the flat-slice hoist resolves it), plus
// per-arm shoulder pads at -15 (right, behind body) and 25 (left, above arm).
// Modern ships no Armor folder; v1's catalogue is Legacy-only (8 entries).
const ARMOR_PARTS = [
  // Legacy. Modern's pack ships no `5_Armor/` folder at all.
  "Armor_1", "Armor_2", "Armor_3", "Armor_4",
  "Armor_5", "Armor_6", "Armor_7", "Armor_8",
  // Ver300. 3-region atlas (Body/Left/Right) — same as Cloth + Legacy Armor.
  // Per-region count varies (some armors are Body-only, some lack a
  // shoulder). SPUM skips `11` and jumps to `12` in this folder.
  "New_Armor_01", "New_Armor_02", "New_Armor_03", "New_Armor_04",
  "New_Armor_05", "New_Armor_06", "New_Armor_07", "New_Armor_08",
  "New_Armor_09", "New_Armor_10", "New_Armor_12",
  // RetroHeroes — class-themed; 9 entries (no Sorceress armor).
  "Armor_Archer_1", "Armor_Archer_2",
  "Armor_Healer_1", "Armor_Healer_2",
  "Armor_Knight_1", "Armor_Knight_2",
  "Armor_Rogue_1", "Armor_Rogue_2",
  "Armor_Sorcerer",
  // Undead. 3-region atlas (Body/Left/Right).
  "Undead_Armor_01", "Undead_Armor_02", "Undead_Armor_03", "Undead_Armor_04",
  "Undead_Armor_05", "Undead_Armor_06", "Undead_Armor_07",
  // Ver121 — single Body-only armor (spriteMode-2 with `Body` region only;
  // the renderer's missing-region skip handles the absent shoulders, same
  // pattern as Ver300's Body-only armor variants).
  "Normal_Armor1",
  // Custom parts — managed by the Part Studio (/admin/spum?tab=parts).
  // custom-parts:BEGIN armor
  // custom-parts:END armor
] as const;

// Back slot — capes, wings, backpacks. Single-region single-sprite atlases.
// Renders on `Root/BodySet/P_Body/P_Back/Back` (sortingOrder -100 — sits
// behind every other slot including the back-of-body right arm at -20).
// Modern ships no Back assets, so v1's catalogue is Legacy-only: three
// mainline cape/wing variants. SPUM's Legacy `7_Back/` also has a tiny
// `BowBack_1` (bow-quiver detail) and a `Soon_Back1` (WIP-flagged source
// asset); both skipped in v1.
const BACK_PARTS = [
  // Legacy. Modern's pack ships no `7_Back/` folder at all.
  "Back_1", "Back_2", "Back_3",
  // Ver300. 2 mainline backs; source `New_Back_02.Png` (capital `.Png`) is
  // renamed to `.png` at copy time by the importer.
  "New_Back_01", "New_Back_02",
  // RetroHeroes — class-themed cape/quiver/wing variants.
  "Back_Archer_1", "Back_Archer_2",
  "Back_Healer_1", "Back_Healer_2",
  "Back_Knight_1", "Back_Knight_2",
  "Back_Rogue_1", "Back_Rogue_2",
  "Back_Sorcerer", "Back_Sorceress",
  // Undead. 2 entries (tattered cloaks).
  "Undead_Back_01", "Undead_Back_02",
  // Custom one-off imports — managed by scripts/custom-part-import.ts.
  // custom-parts:BEGIN back
  // custom-parts:END back
] as const;

// Right-hand weapon (held prop). The prefab has 15 weapon entries
// (L/R weapons + shields + slung), but SPUM's own runtime + our v1 wire
// only the right-hand main weapon. Single-region single-sprite atlases
// with custom per-asset pivots tuned so the grip lands on the bone origin.
// Modern's 11 entries are "everyday objects" (no swords/bows), perfect for
// accounting content: laptop, coffee, clipboard, phone, mic, map, etc.
// Renders on R_Weapon (sortingOrder -15 — between the back-of-body right arm
// at -20 and the body sprite, so the prop sits naturally in front of the arm
// but visually correct relative to the body silhouette).
const WEAPON_PARTS = [
  // ModernPackVer1 — `6_Weapons/7_Others/` only (Modern ships no
  // swords/bows/axes; those land later with Ver300/RetroHeroes).
  "Weapon_m_beer", "Weapon_m_board", "Weapon_m_coffee",
  "Weapon_m_laptop", "Weapon_m_map", "Weapon_m_mic",
  "Weapon_m_pan", "Weapon_m_phone", "Weapon_m_pouch",
  "Weapon_m_shovel", "Weapon_m_surf",
  // Ver300 — combat weapons across 8 subfolders under `8_Weapons/`. Part keys
  // are `<Type>_NN` where `NN` is the shared numbering across the whole
  // `8_Weapons/` tree (so e.g. `Sword_01` and `Spear_09` reuse SPUM's
  // numbering verbatim). Non-shield weapons render on R_Weapon (or L_Weapon
  // for weapon2); shields are routed to R_Shield/L_Shield by SpumCharacter
  // so the ±45° P_Shield grip pose holds them across the body.
  "Sword_01", "Sword_06", "Sword_17", "Sword_18", "Sword_19", "Sword_20",
  "Spear_09", "Spear_13", "Spear_14", "Spear_16",
  "Axe_02", "Axe_04", "Axe_08",
  "Bow_10", "Bow_12", "Bow_15",
  "Wand_03",
  "Dagger_05", "Dagger_11",
  "Shield_01", "Shield_02", "Shield_03", "Shield_04",
  "Mace_07",
  // RetroHeroes — class-themed weapons. 14 entries across sword/bow/shield/
  // wand/dagger subfolders. Non-shield weapons render on R_Weapon/L_Weapon;
  // shields route to R_Shield/L_Shield (the P_Shield ±45° grip bone).
  "Weapon_Knight_1", "Weapon_Knight_2",
  "Weapon_Archer_1", "Weapon_Archer_2",
  "Shield_Knight_1", "Shield_Knight_2",
  "Shield_Sorcerer", "Shield_Sorceress",
  "Weapon_Healer_1", "Weapon_Healer_2",
  "Weapon_Sorcerer", "Weapon_Sorceress",
  "Weapon_Rogue_1", "Weapon_Rogue_2",
  // Undead. 13 entries across sword/axe/bow/wand subfolders + 3 shields. The
  // weapon numbering (01..10) spans the whole 6_Weapons/ tree — same flat
  // namespace convention as Ver300.
  "Undead_Weapon_01", "Undead_Weapon_02", "Undead_Weapon_03", "Undead_Weapon_04",
  "Undead_Weapon_05", "Undead_Weapon_06", "Undead_Weapon_07", "Undead_Weapon_08",
  "Undead_Weapon_09", "Undead_Weapon_10",
  "Undead_Shield_01", "Undead_Shield_02", "Undead_Shield_03",
  // Ver121 — 3 axes + 4 wooden shields + 1 steel shield from the original
  // Knight pack. Axes render on R_Weapon/L_Weapon; shields route to
  // R_Shield/L_Shield (the P_Shield ±45° grip bone).
  "AxeLong1", "AxeNormal1", "AxeSmall1",
  "SteelShield1", "WoodShield1", "WoodShield2", "WoodShield3", "WoodShield4",
  // Custom one-off imports — managed by scripts/custom-part-import.ts.
  // custom-parts:BEGIN weapon
  "Custom_Whisk",
  // custom-parts:END weapon
] as const;

// `pathSlot` parameter (vs deriving the URL from the slot key) lets two slots
// share the same `/public/spum/sprites/<folder>/` tree. SPUM does the same in
// Unity: the prefab has separate L_Weapon and R_Weapon SpriteRenderers that
// both reference the single `6_Weapons/` asset folder. weapon + weapon2 mirror
// that — one set of PNGs/atlases, two bone bindings.
function asMap<P extends string>(
  pathSlot: string,
  parts: readonly P[],
): { [K in P]: string } {
  const out = {} as { [K in P]: string };
  for (const part of parts) out[part] = `/spum/sprites/${pathSlot}/${part}.png`;
  return out;
}

export const SPUM_SPRITES = {
  body: asMap("body", BODY_PARTS),
  hair: asMap("hair", HAIR_PARTS),
  cloth: asMap("cloth", CLOTH_PARTS),
  pant: asMap("pant", PANT_PARTS),
  eye: asMap("eye", EYE_PARTS),
  helmet: asMap("helmet", HELMET_PARTS),
  faceHair: asMap("faceHair", FACEHAIR_PARTS),
  weapon: asMap("weapon", WEAPON_PARTS),
  // Left-hand weapon — shares the `/spum/sprites/weapon/` folder with the
  // right hand (no second copy on disk). The only difference is the bone
  // binding in SLOT_REGION_TO_BONE (L_Weapon vs R_Weapon).
  weapon2: asMap("weapon", WEAPON_PARTS),
  back: asMap("back", BACK_PARTS),
  armor: asMap("armor", ARMOR_PARTS),
} as const;

export type SpumSlot = keyof typeof SPUM_SPRITES;
export type SpumPart<S extends SpumSlot> = keyof (typeof SPUM_SPRITES)[S];

export type BodyPart = SpumPart<"body">;
export type HairPart = SpumPart<"hair">;
export type ClothPart = SpumPart<"cloth">;
export type PantPart = SpumPart<"pant">;
export type EyePart = SpumPart<"eye">;
export type HelmetPart = SpumPart<"helmet">;
export type FaceHairPart = SpumPart<"faceHair">;
export type WeaponPart = SpumPart<"weapon">;
export type Weapon2Part = SpumPart<"weapon2">;
export type BackPart = SpumPart<"back">;
export type ArmorPart = SpumPart<"armor">;

// E13f — used by the `Paired Random` button in `SpumDebugHarness` to split the
// weapon catalogue into shields vs main weapons. Mirrors original SPUM's
// `IsShield()` in `SPUM_ImprovedTagManager.cs:1809`, which checks
// `Type=="shield"` / filename / properties — we don't carry that metadata, so
// we match by name. Every shield in the imported packs has "shield" in its
// part key (Ver300 `Shield_*`, RetroHeroes `Shield_*`, Undead `Undead_Shield_*`,
// Ver121 `SteelShield*` / `WoodShield*`), so the substring match is reliable;
// any future shield import that breaks the convention should be added to the
// set explicitly.
export const SHIELD_WEAPON_KEYS: ReadonlySet<WeaponPart> = new Set(
  (WEAPON_PARTS as readonly string[]).filter((k) =>
    k.toLowerCase().includes("shield"),
  ) as WeaponPart[],
);

export function isShieldPart(part: WeaponPart): boolean {
  return SHIELD_WEAPON_KEYS.has(part);
}

// Editor-side pack / class membership. The importer keeps each upstream pack's
// naming convention verbatim (Modern's `_m##` suffix, Legacy's bare names,
// Ver300's `New_` prefix, RetroHeroes' class-themed suffixes, Undead's
// `Undead_` / `Zombie_` prefixes, Ver121's `Normal_` prefix), so pack
// membership is recoverable from the part key. Used by `SpumPartPicker` to let
// authors narrow a slot with hundreds of imported parts down to one pack /
// class without scrolling.
export type SpumPack =
  | "Modern"
  | "Legacy"
  | "Ver300"
  | "RetroHeroes"
  | "Undead"
  | "Ver121"
  | "Custom";

export const SPUM_PACKS: readonly SpumPack[] = [
  "Modern",
  "Legacy",
  "Ver300",
  "RetroHeroes",
  "Undead",
  "Ver121",
  "Custom",
];

// RetroHeroes is the only pack whose parts are class-themed; the other packs
// have no `class` axis at all. SPUM ships no `Mage` parts (the magic-user
// archetype is split into `Sorcerer` / `Sorceress`).
export const SPUM_CLASSES = [
  "Knight",
  "Archer",
  "Rogue",
  "Healer",
  "Sorcerer",
  "Sorceress",
] as const;
export type SpumClass = (typeof SPUM_CLASSES)[number];

const RETRO_CLASS_RE = /_(Knight|Archer|Rogue|Healer|Sorcerer|Sorceress)(?:_|$)/;

// Ver300's weapon part keys use SPUM's own flat numbering (`Sword_01`,
// `Spear_09`, …) without a `New_` prefix. Restricted to weapon slots so the
// regex doesn't accidentally claim e.g. a future non-weapon `Shield_*` part.
const VER300_WEAPON_RE = /^(?:Sword|Spear|Axe|Bow|Wand|Dagger|Shield|Mace)_\d/;

// Ver121 weapons predate the `Normal_` prefix convention; SPUM ships them with
// bespoke names (`AxeLong1`, `WoodShield3`, …). Same scope note as above.
const VER121_WEAPON_RE = /^(?:AxeLong|AxeNormal|AxeSmall|SteelShield|WoodShield)\d+$/;

// Modern cloth uses no shared prefix — each base outfit is named directly
// (`dress_`, `farmer`, `hoodie`, `suit_`, `tee_`, `winter`) with `_c#` / `_g`
// recolour suffixes. Centralised so additions stay easy to spot.
const MODERN_CLOTH_PREFIXES = [
  "dress_",
  "farmer",
  "hoodie",
  "suit_",
  "tee_",
  "winter",
];

function isModernPart(slot: SpumSlot, part: string): boolean {
  switch (slot) {
    case "hair":
    case "helmet":
      // Modern hairs / helmets carry an `_m##` token (`Hair_m01`,
      // `Helmet_m07_brown`). The digit after `_m` distinguishes them from
      // RetroHeroes `Helmet_<Class>_1` (already caught earlier).
      return /_m\d/.test(part);
    case "pant":
      return part.startsWith("Foot_m");
    case "cloth":
      return MODERN_CLOTH_PREFIXES.some((base) => part.startsWith(base));
    case "faceHair":
      return part.startsWith("face_");
    case "weapon":
    case "weapon2":
      return part.startsWith("Weapon_m");
    default:
      // Modern ships no native body / eye / back / armor parts (Modern's
      // prefab references Legacy's `Human_1` body, which stays catalogued
      // under Legacy here).
      return false;
  }
}

export function packOfPart<S extends SpumSlot>(
  slot: S,
  part: SpumPart<S>,
): SpumPack {
  const p = part as string;
  // One-off parts imported via scripts/custom-part-import.ts.
  if (p.startsWith("Custom_")) return "Custom";
  if (p.startsWith("Undead_") || p.startsWith("Zombie_")) return "Undead";
  if (p.startsWith("New_")) return "Ver300";
  if (RETRO_CLASS_RE.test(p)) return "RetroHeroes";
  if (p.startsWith("Normal_")) return "Ver121";
  if (slot === "weapon" || slot === "weapon2") {
    if (VER121_WEAPON_RE.test(p)) return "Ver121";
    if (isModernPart(slot, p)) return "Modern";
    if (VER300_WEAPON_RE.test(p)) return "Ver300";
    return "Legacy";
  }
  if (isModernPart(slot, p)) return "Modern";
  return "Legacy";
}

export function classOfPart<S extends SpumSlot>(
  slot: S,
  part: SpumPart<S>,
): SpumClass | null {
  void slot;
  const m = (part as string).match(RETRO_CLASS_RE);
  return m ? (m[1] as SpumClass) : null;
}

// E23 — Hair-mask-under-helmet. SPUM 1.8.0's "MaskToggle on helmet button"
// flips hair's Unity `SpriteRenderer.maskInteraction` to `VisibleInsideMask`
// against a head-silhouette SpriteMask on the `5_Head` bone, clipping tall
// hair to the head shape. In our composited render the helmet already
// covers the visible-head fragment for any helmet wider than the
// silhouette, so v1 collapses the mask semantics to "hide hair entirely
// when the helmet's mask is on" — see Phase E23 in
// docs/spum-engine-completeness.md for the scope decision.
//
// Default: every imported helmet hides hair (matches SPUM's MaskToggle
// default of ON). Entries listed here opt OUT — hair stays visible
// underneath. Curate as visual verification surfaces hair-friendly helmets
// (knit caps, headbands, small soft hats); start empty.
export const HELMET_HAIR_PASSTHROUGH: ReadonlySet<HelmetPart> = new Set<HelmetPart>([
  // Curated as authoring needs surface — start empty.
]);

export function helmetHidesHair(part: HelmetPart): boolean {
  return !HELMET_HAIR_PASSTHROUGH.has(part);
}

// Every `"<slot>:<region>"` slice key the rig can draw — the addressable
// pieces of a character. `SceneAaRef.hideSlices` names keys from this list to
// drop an individual limb (an amputee, a part hidden under a prop) rather
// than a whole slot.
//
// The authority is `SLOT_REGION_TO_BONE` in `SpumCharacter.tsx`, but that
// module pulls in React and this one is imported by the node-side content
// validator, so the list is mirrored here instead of derived.
// `sliceKeys.test.ts` fails if the two ever drift apart.
export const SCENE_SLICE_KEYS = [
  "body:Head",
  "body:Body",
  "body:Arm_L",
  "body:Arm_R",
  "body:Foot_L",
  "body:Foot_R",
  "faceHair:FaceHair",
  "hair:Hair",
  "cloth:Body",
  "cloth:Right",
  "cloth:Left",
  "pant:Right",
  "pant:Left",
  "eye:Back",
  "eye:Front",
  "eye:Free",
  "helmet:Helmet",
  "weapon:Weapon",
  "weapon2:Weapon",
  "back:Back",
  "armor:Body",
  "armor:Right",
  "armor:Left",
] as const;

export type SceneSliceKey = (typeof SCENE_SLICE_KEYS)[number];

export const SPUM_PART_LIST = {
  body: BODY_PARTS,
  hair: HAIR_PARTS,
  cloth: CLOTH_PARTS,
  pant: PANT_PARTS,
  eye: EYE_PARTS,
  helmet: HELMET_PARTS,
  faceHair: FACEHAIR_PARTS,
  weapon: WEAPON_PARTS,
  weapon2: WEAPON_PARTS,
  back: BACK_PARTS,
  armor: ARMOR_PARTS,
} as const;

// Per-character colour customization (E1). Hex strings (e.g. `#7d4a2a`)
// multiplied per-pixel into each slot's source PNG via SVG `<feColorMatrix>`
// at render time — mirrors Unity's `SpriteRenderer.color` mechanic. Missing
// entry = no tint (source PNG renders as-is). `eyeIris` is a separate
// addressable channel because SPUM's prefab tints Eye Front and Eye Back
// independently and ships `ignoreColorPart: [Back]` so the "eye colour"
// button only affects the iris (Front) — see Decisions Log entry "Eye tint
// follows SPUM's `ignoreColorPart: [Back]`". Without `eyeIris`, `colors.eye`
// falls through to the iris too; the sclera is always white.
export type CharacterColors = Partial<Record<SpumSlot | "eyeIris", string>>;

// Re-exported from `./appearance` so consumers of CharacterConfig get the
// type alongside it — the appearance module owns the helper + presets, this
// file owns the schema surface.
export type { AppearanceFields, AppearancePerSlot } from "./appearance";
import type { AppearanceFields, AppearancePerSlot } from "./appearance";

export type CharacterConfig = {
  body: BodyPart;
  // Optional. When omitted no hair renders — head is bald. SPUM ships no
  // dedicated "bald" sprite; the bone simply has no slice attached, same
  // pattern as the other optional slots below.
  hair?: HairPart;
  // Optional. When omitted no cloth renders — the body's bare torso/arms show
  // through, same "no slice attached" pattern as `hair` above. Useful for
  // bare-bodied characters (zombies, monsters) and for skipping addon-pack
  // cloth assets that are near-empty or mis-pivoted on the shared skeleton.
  cloth?: ClothPart;
  pant: PantPart;
  // Optional. When omitted the head is featureless (Modern's body Head slice
  // ships intentionally blank). When set, the eye sprite renders on
  // P_LEye/P_REye; Eye_Close.png always loads alongside for the
  // P_LClose/P_RClose bones — clip visibility tracks (m_IsActive) toggle
  // between them.
  eye?: EyePart;
  // Optional. When omitted no helmet renders. When set, the sprite renders on
  // the Front helmet bone (12_Helmet2, sortingOrder 12) — above hair and the
  // head, but under the eyes: eye bones are lifted to 14/15 so a brow band
  // never slices through a wide/free eye layer (see EYE_Z_LIFT in
  // SpumCharacter). SPUM's prefab also exposes a Back helmet bone (11_Helmet1) but the
  // SPUM runtime only ever assigns user picks to Front; we follow that.
  helmet?: HelmetPart;
  // Optional face accessory — Modern's `face_lip` is the only path to a
  // visible mouth (the body Head slice ships blank); other Modern entries
  // are blush, eyelash, glasses; Legacy entries are mustaches/beards. Renders
  // on P_Mustache/6_FaceHair (sortingOrder 5, same z as 5_Head — slot
  // ordering in SLOT_REGION_TO_BONE places faceHair AFTER body so the sprite
  // paints on top of the head).
  faceHair?: FaceHairPart;
  // Optional right-hand held prop. When set, the sprite renders on the
  // R_Weapon bone (sortingOrder -15) — between the right arm (-20) and the
  // body, so the prop tracks the arm naturally through clips like greeting1.
  // Modern's catalogue is everyday objects (laptop, coffee, mic, etc.) — no
  // swords or bows in v1.
  weapon?: WeaponPart;
  // Optional left-hand held prop. Same parts catalogue as `weapon`, just
  // bound to the L_Weapon bone (sortingOrder 19 — just behind the front-arm
  // L_Arm at z=20 so the arm hides the grip while the blade sticks past
  // it). SPUM's prefab carries both L_Weapon and R_Weapon SpriteRenderer
  // slots; only the runtime UI hardwired the user pick to R_Weapon. This
  // exposes the left-hand slot using the same asset folder — equivalent to
  // dragging a sprite onto SPUM's L_Weapon renderer in the prefab. Tint and
  // per-slot appearance are independent of `weapon` (separate channels in
  // `colors` and `appearancePerSlot`), matching SPUM's per-SpriteRenderer
  // colour model.
  weapon2?: Weapon2Part;
  // Optional back attachment — cape, wings, backpack. Renders on the Back
  // bone (sortingOrder -100), so it sits behind every other slot (including
  // the back-of-body right arm at -20). Modern ships no Back assets; v1's
  // catalogue is Legacy-only (`Back_1`/`_2`/`_3`).
  back?: BackPart;
  // Optional armor — chest/shoulder overlay over the body and arms. The
  // sprite atlas has three regions (`Body`, `Right`, `Left`) which render on
  // separate bones: `BodyArmor` (z=2), `-15_R_Shoulder` (z=-15), and
  // `25_L_Shoulder` (z=25) — same pattern as the existing Cloth slot. Modern
  // ships no Armor assets; v1's catalogue is Legacy-only.
  armor?: ArmorPart;
  // Optional per-slot tint map. See `CharacterColors` doc above.
  colors?: CharacterColors;
  // Optional global appearance dial (E1c) — six CSS filter functions
  // (hue/saturation/brightness/contrast/sepia/blur) applied to the whole
  // character on the SpumCharacter root div. See `AppearanceFields` in
  // `./appearance` for ranges + identity values. Missing entry / identity =
  // no filter applied (rendered DOM stays byte-identical to today).
  appearance?: AppearanceFields;
  // Optional per-slot appearance dial. Each slot's filter composes onto its
  // colour-tint filter on every slice that belongs to that slot. The result
  // composes again with the global `appearance` on the root div: the
  // effective chain per slice is `tint → per-slot filter → global filter`.
  appearancePerSlot?: AppearancePerSlot;
  // E23 — hair-mask-under-helmet override. Mirrors SPUM 1.8.0's per-helmet
  // MaskToggle, lifted to a per-actor control so authors can override the
  // catalogue default without per-helmet UI churn.
  //   - "auto" (default / undefined): follow the helmet's flag — hair is
  //     hidden iff `config.helmet` is set AND that helmet hides hair
  //     (i.e. not in `HELMET_HAIR_PASSTHROUGH`)
  //   - "on": hair hidden whenever `config.helmet` is set, regardless of
  //     the helmet's flag
  //   - "off": hair shown whenever `config.helmet` is set, regardless of
  //     the helmet's flag
  // When no helmet is set, this field is a no-op — hair always renders.
  hairMask?: "auto" | "on" | "off";
};

// E23 — resolves whether the renderer should drop the hair slices for a
// given character. Pure function over CharacterConfig; consumers (renderer,
// editors, tests) call this rather than re-implementing the precedence
// rule. Returns false when `config.helmet` is undefined regardless of
// `hairMask` — the toggle only matters when a helmet is present.
export function resolveHideHair(config: CharacterConfig): boolean {
  if (config.helmet === undefined) return false;
  const override = config.hairMask ?? "auto";
  if (override === "off") return false;
  if (override === "on") return true;
  return helmetHidesHair(config.helmet);
}

export function spritePath<S extends SpumSlot>(slot: S, part: SpumPart<S>): string {
  return SPUM_SPRITES[slot][part] as string;
}

// Every sprite asset has a sibling `.atlas.json` next to its PNG that the
// renderer fetches to slice + pivot the texture per bone. Multi-region assets
// (body, cloth, pant) get one named region per Unity sprite-sheet slice;
// single-sprite assets (hair) get a single full-image region using the meta's
// top-level `spritePivot`. Path derived from the PNG path so the catalog
// stays in lockstep with imports.
export function atlasPath<S extends SpumSlot>(slot: S, part: SpumPart<S>): string {
  return spritePath(slot, part).replace(/\.png$/, ".atlas.json");
}

// Clip names match the JSON files emitted by the importer under
// `public/spum/anims/`. The two `4_Death/` collisions get a `death_` prefix
// so `sit`/`sleep` keep their unprefixed `6_Other/` names. E8 added 11
// combat/reaction clips sourced from Legacy (`attack_*`, `skill_*`, plus
// `damaged`/`die`/`debuff_stun`/`concentrate`/`buff`) — every bone path the
// clips animate exists in Modern's skeleton (only Legacy's `Shadow` bone is
// orphaned and silently ignored), so Modern characters can play them
// directly without a compat shim.
export const SPUM_ANIMATIONS = [
  "idle", "sit_idle", "sleep_idle",
  "move", "run", "run2",
  "death_sit", "death_sleep",
  "greeting1", "greeting2", "greeting3",
  "jump", "jump2",
  "sit", "sleep",
  "attack_melee", "skill_melee",
  "attack_bow", "skill_bow",
  "attack_magic", "skill_magic",
  "damaged", "die", "debuff_stun",
  "concentrate", "buff",
  // E9 — Ver300 weapon-specific clips. `short_sword_attack` is the cleaned
  // name for SPUM's `ShotSwordAttack_1.anim` (upstream typo). No engine-level
  // auto-routing between weapon picks and these clips — authors choose both
  // manually. Bone paths verified pose-compatible with Modern's skeleton
  // (`Shadow` is the same Legacy-style orphan and is silently ignored).
  "long_spear_idle", "long_spear_walk",
  "axe_attack", "long_spear_attack", "short_sword_attack",
  // Hand-authored derivative of `axe_attack` — truncated to t=0.35 so only
  // the first forward strike plays (the second overhead chop is cut). Reads
  // as a throw-release: arm whips forward, body winds back, animation ends
  // holding the post-release pose.
  "throw",
  // Hand-authored composite: legs (P_LFoot/P_RFoot) + body bob from `move`,
  // arms (P_LArm/P_RArm) from `greeting2`. Reads as "walking while carrying
  // something" — arms held forward instead of swinging. One-shot transition
  // (arms ramp into the carry pose); chain into `move_carry_loop` for the
  // sustained walk-while-carrying.
  "move_carry",
  // Hand-authored loop companion to `move_carry`. Legs + body bob continue
  // the walk cycle from `move`; arms are LOCKED in the held-carry pose
  // (P_LArm/P_RArm reduced to one rot kf each, pos held constant). Safe to
  // loop because every track returns to its t=0 value at t=duration.
  "move_carry_loop",
  // Hand-authored derivative of `long_spear_idle` — right arm ramps from the
  // held pose out to an extended reach over the clip's length. Reads as
  // taking something offered; play as a one-shot. `give` is the exact time-
  // reversal (arm starts extended, pulls back in) for handing something over.
  "receive", "give",
  // Concatenation of `give` then `receive` in one clip (seam key deduped —
  // give ends on the exact pose receive starts from). Reads as handing
  // something over and then taking something back; play as a one-shot.
  "givereceive",
  // Hand-authored exact time-reversal of `death_sleep` (the engine has no
  // reverse playback — SceneActor/play `speed` must be positive). Holds the
  // lying pose for the first half, then rises to standing over the second.
  // Ends on death_sleep's t=0 standing pose, so chain into `idle`.
  "getup",
] as const;

export type SpumAnimation = (typeof SPUM_ANIMATIONS)[number];

// AA-original clips — authored in `lib/aachar/clips/` with no SPUM
// counterpart. They resolve through the AA clip library
// (`compiledAaClip` → `AA_CLIPS`), so they play on a `SceneActor.aachar`
// actor and ONLY on one: a SPUM-config actor falls through to fetching
// SPUM's clip by name and 404s. `content/validation.ts` enforces that.
//
// Kept as a literal here rather than derived from `AA_CLIPS` so the Zod
// enum stays a cheap import; `catalog.test.ts` fails if the two drift.
export const AA_ONLY_ANIMATIONS = [
  "fall_forward",
  "move_1handcarryup_loop",
  "move_2handcarry_loop",
  "move_2handcarryup_loop",
  "stab",
  "uppercut",
  "yay",
  "zombie_walk",
] as const;

export type AaOnlyAnimation = (typeof AA_ONLY_ANIMATIONS)[number];

// Every clip name a scene may name. Actors resolve it per rig (§25.4):
// model override → AA library → SPUM by name.
export const SCENE_ANIMATIONS = [...SPUM_ANIMATIONS, ...AA_ONLY_ANIMATIONS] as const;

export type SceneAnimation = SpumAnimation | AaOnlyAnimation;

// E22f — curated subset of clips that read correctly on a SceneActor with a
// `mount` (i.e. seated on a horse). Excludes anything that animates the legs
// in a way that conflicts with the seated/saddled lower body (`move`/`run`,
// `jump`, `sleep*`, `move_carry*`) and anything that assumes the actor is
// standing on the ground (`idle`, `greeting*` — wave gestures rely on
// upright posture; if you want a mounted wave, add it here and verify in
// the Horse harness). Upper-body / pose-only clips dominate the list since
// the saddle locks the lower body.
//
// Not enforced at the engine level — `<SpumCharacter>` will happily play any
// clip on a mounted rider. The editor uses this list to surface mount-
// appropriate options first in the Action row's animation dropdown when the
// row's actor has a mount; the full SPUM_ANIMATIONS list is still reachable
// via the "All" group below.
export const MOUNTED_RIDER_ANIMATIONS: readonly SpumAnimation[] = [
  "sit_idle",
  "damaged",
  "die",
  "death_sit",
  "concentrate",
  "buff",
  "attack_melee",
  "skill_melee",
  "attack_bow",
  "skill_bow",
  "attack_magic",
  "skill_magic",
  "short_sword_attack",
  "axe_attack",
  "long_spear_attack",
  "long_spear_idle",
  "throw",
];
